#
# Onedrive ubuntu client running inside docker container
#
# docker-compose build


data:
  # Note you cannot scale if you use conteiner_name
  container_name: onedrive-data
  build: docker
  dockerfile: Dockerfile
  environment:
    - APP_CLIENT_ID=0000000040172910
    - APP_CLIENT_SECRET=WAltBcwM9B3nlGDmplOUGfPLqsw5bHDA
    - LOGNAME=onedrive 
    - USER=onedrive
    - SUDO_USER=root
    - LC_ALL=C.UTF-8
    - LANG=C.UTF-8
  hostname: onedrive
  volumes:
    - ./onedrive:~/.onedrive
    - ./data:/root/OneDrive/  
    - ./logs:/var/log/
  ports:
    # for ssh
    - "6333:22"
  restart: on-failure:5

